
name: 'dbt_core_project'
version: '1.0.0'

profile: 'dbt_core_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"

models:
  dbt_core_project:
    staging:
      schema: staging
      materialized: table
      tags: ['staging']

    intermediate:
      materialized: ephemeral
      tags: ['intermendiate']

    marts:
      schema: marts
      materialized: table
      tags: ['marts']